apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../serviceaccount.yaml
  - ../../configmap.yaml
  - ../../service.yaml
  - ../../deployment.yaml
  - ../../cronjob.yaml
  - secretproviderclass.yaml

patches:
  - target:
      kind: Deployment
      name: laas
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: signing-key
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: laas-signing-key
