apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: laas-signing-key
  labels:
    app.kubernetes.io/name: laas
    app.kubernetes.io/component: ledger-service
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com"
    roleName: "CHANGE_ME"
    objects: |
      - objectName: "cosign.key"
        secretPath: "secret/data/CHANGE_ME_VAULT_PATH"
        secretKey: "cosign_private_key"
