apiVersion: v1
kind: Secret
metadata:
  name: laas-signing-key
  labels:
    app.kubernetes.io/name: laas
    app.kubernetes.io/component: ledger-service
type: Opaque
stringData:
  cosign.key: |
    -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
    CHANGE_ME
    -----END ENCRYPTED SIGSTORE PRIVATE KEY-----
