apiVersion: v1
kind: Service
metadata:
  name: laas
  labels:
    app.kubernetes.io/name: laas
    app.kubernetes.io/component: ledger-service
spec:
  selector:
    app.kubernetes.io/name: laas
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
