from __future__ import annotations

LAYER_FILE_SUFFIX = ".json"

EVENT_KEY_LAYER_ID = "layer_id"
EVENT_KEY_FINDING_REF = "finding_ref"
EVENT_KEY_FINDING_FINGERPRINT = "finding_fingerprint"
EVENT_KEY_DECISION = "decision"
EVENT_KEY_VERDICT = "verdict"
EVENT_KEY_RATIONALE = "rationale"
EVENT_KEY_JUSTIFICATION = "justification"
EVENT_KEY_RECORDED_AT = "recorded_at"
EVENT_KEY_SEVERITY = "severity"
EVENT_KEY_ACTOR = "actor"
EVENT_KEY_DISPOSITION = "disposition"
EVENT_KEY_SOURCE = "source"

LAYER_KEY_EVENTS = "events"
LAYER_KEY_METADATA = "metadata"
METADATA_KEY_MERKLE_EPOCH = "merkle_epoch"
METADATA_KEY_MERKLE_ROOT = "merkle_root"

__all__ = [
    "EVENT_KEY_ACTOR",
    "EVENT_KEY_DECISION",
    "EVENT_KEY_DISPOSITION",
    "EVENT_KEY_FINDING_FINGERPRINT",
    "EVENT_KEY_FINDING_REF",
    "EVENT_KEY_JUSTIFICATION",
    "EVENT_KEY_LAYER_ID",
    "EVENT_KEY_RATIONALE",
    "EVENT_KEY_RECORDED_AT",
    "EVENT_KEY_SEVERITY",
    "EVENT_KEY_SOURCE",
    "EVENT_KEY_VERDICT",
    "LAYER_FILE_SUFFIX",
    "LAYER_KEY_EVENTS",
    "LAYER_KEY_METADATA",
    "METADATA_KEY_MERKLE_EPOCH",
    "METADATA_KEY_MERKLE_ROOT",
]
