apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: laas-signing-key
  labels:
    app.kubernetes.io/name: laas
    app.kubernetes.io/component: ledger-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: CHANGE_ME_SECRET_STORE
    kind: SecretStore
  target:
    name: laas-signing-key
    creationPolicy: Owner
  data:
    - secretKey: cosign.key
      remoteRef:
        key: CHANGE_ME_REMOTE_KEY
        property: cosign_private_key
