"""Ledger integrity package — Merkle tree primitives, stamping, and verification."""

from .ledger import (
    IntegrityFinding,
    Severity,
    SignAttempt,
    sign_if_configured,
    stamp_and_sign,
    stamp_merkle_metadata,
    verify_merkle_integrity,
    verify_merkle_signature,
)
from .merkle import (
    canonical_event_bytes,
    compute_merkle_root,
    compute_pre_epoch_checkpoint,
    compute_root,
    consistency_proof,
    inclusion_proof,
    leaf_hash,
    node_hash,
    verify_consistency,
    verify_inclusion,
)
from .signing import (
    CosignBackend,
    SigningBackend,
    SigningConfig,
    SignResult,
    SigstoreOIDCBackend,
    VerifyResult,
    get_backend,
    get_backend_for_method,
    get_backend_from_config,
)

__all__ = [
    "CosignBackend",
    "IntegrityFinding",
    "Severity",
    "SignAttempt",
    "SignResult",
    "SigningBackend",
    "SigningConfig",
    "SigstoreOIDCBackend",
    "VerifyResult",
    "canonical_event_bytes",
    "compute_merkle_root",
    "compute_pre_epoch_checkpoint",
    "compute_root",
    "consistency_proof",
    "get_backend",
    "get_backend_for_method",
    "get_backend_from_config",
    "inclusion_proof",
    "leaf_hash",
    "node_hash",
    "sign_if_configured",
    "stamp_and_sign",
    "stamp_merkle_metadata",
    "verify_consistency",
    "verify_inclusion",
    "verify_merkle_integrity",
    "verify_merkle_signature",
]
